# Generated by Django 5.0.6 on 2024-06-25 11:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedpolicy',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
