# Generated by Django 5.0.6 on 2024-06-29 15:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_manager', '0002_alter_purchasedpolicy_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('policy_type', models.CharField(choices=[('travel', 'Travel Insurance'), ('health', 'Health Insurance'), ('2wheeler', '2 Wheeler Insurance'), ('other', 'Other Insurance')], default='other', max_length=20)),
                ('base_premium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_months', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='purchasedpolicy',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='policy_available', to='policy_manager.policy'),
        ),
    ]
