# Generated by Django 5.0.6 on 2024-06-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_manager', '0003_policy_purchasedpolicy_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='policy_type',
            field=models.CharField(choices=[('travel', 'Travel Insurance'), ('health', 'Health Insurance'), ('2wheeler', '2 Wheeler Insurance'), ('other', 'Other Insurance'), ('home', 'Home Insurance')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchasedpolicy',
            name='policy_type',
            field=models.CharField(choices=[('travel', 'Travel Insurance'), ('health', 'Health Insurance'), ('2wheeler', '2 Wheeler Insurance'), ('other', 'Other Insurance'), ('home', 'Home Insurance')], db_index=True, default='other', max_length=20),
        ),
    ]
