export const cardData = [
    { id: 1, icon: '❤️', label: 'Health Insurance', className: 'health', backgroundColor: '#e6f7ff', category: 'Health' },
    { id: 2, icon: '✈️', label: 'Travel Insurance', className: 'travel', backgroundColor: '#f0f5ff', category: 'Travel' },
    { id: 3, icon: '☂️', label: 'Life Insurance', className: 'life', backgroundColor: '#fffbe6', category: 'Life' },
    { id: 4, icon: '🚗', label: 'Auto Insurance', className: 'auto', backgroundColor: '#fff1f0', category: 'Property' },
    { id: 5, icon: '🏠', label: 'Home Insurance', className: 'home', backgroundColor: '#e6f7ff', category: 'Property' },
    { id: 6, icon: '🚑', label: 'Medical Insurance', className: 'medical', backgroundColor: '#f0f5ff', category: 'Health' },
    { id: 7, icon: '📱', label: 'Mobile Insurance', className: 'mobile', backgroundColor: '#fffbe6', category: 'Electronics' },
    { id: 8, icon: '📺', label: 'Home Appliance Insurance', className: 'appliance', backgroundColor: '#e6f7ff', category: 'Electronics' },
    { id: 9, icon: '💻', label: 'Computer Insurance', className: 'computer', backgroundColor: '#e6f7ff', category: 'Electronics' },
    { id: 10, icon: '📷', label: 'Camera Insurance', className: 'camera', backgroundColor: '#fff1f0', category: 'Electronics' },
    { id: 11, icon: '🎮', label: 'Gaming Console Insurance', className: 'console', backgroundColor: '#e6f7ff', category: 'Electronics' },
    { id: 12, icon: '🎧', label: 'Headphone Insurance', className: 'headphone', backgroundColor: '#f0f5ff', category: 'Electronics' },
    { id: 13, icon: '🛳️', label: 'Boat Insurance', className: 'boat', backgroundColor: '#e6f7ff', category: 'Property' },
    { id: 14, icon: '🏍️', label: 'Motorcycle Insurance', className: 'motorcycle', backgroundColor: '#fffbe6', category: 'Property' },
    { id: 15, icon: '🛵', label: 'Scooter Insurance', className: 'scooter', backgroundColor: '#f0f5ff', category: 'Property' },
    { id: 16, icon: '🏢', label: 'Commercial Property Insurance', className: 'commercial-property', backgroundColor: '#fff1f0', category: 'Property' },
    { id: 17, icon: '👨‍💼', label: 'Professional Liability Insurance', className: 'professional-liability', backgroundColor: '#e6f7ff', category: 'Business' },
    { id: 18, icon: '🏥', label: 'Hospital Insurance', className: 'hospital', backgroundColor: '#fffbe6', category: 'Health' },
    { id: 19, icon: '🚲', label: 'Bicycle Insurance', className: 'bicycle', backgroundColor: '#f0f5ff', category: 'Property' },
    { id: 20, icon: '🌾', label: 'Crop Insurance', className: 'crop', backgroundColor: '#fff1f0', category: 'Agriculture' },
    { id: 21, icon: '🐄', label: 'Livestock Insurance', className: 'livestock', backgroundColor: '#e6f7ff', category: 'Agriculture' },
    { id: 22, icon: '👶', label: 'Child Insurance', className: 'child', backgroundColor: '#fffbe6', category: 'Life' },
    { id: 23, icon: '🧳', label: 'Baggage Insurance', className: 'baggage', backgroundColor: '#f0f5ff', category: 'Travel' },
    { id: 24, icon: '🏦', label: 'Mortgage Insurance', className: 'mortgage', backgroundColor: '#fff1f0', category: 'Property' },
];
